### ISSUE TITLE
simplify where part or use a string based syntax?

### ISSUE THREAD

**Issue by pwFoo** [delirius325/MySimpleORM#10]
Where with more than one condition is much to write. 
```
$wheres = array(
    "column" => "IDCompanies",
    "condition" => "=",
    "value" => 1 //keep in mind you could use a sub-query here
);
```
Would a simpler syntax be possible?

Or as another way to do it... string based "selector"?
Something like:
```
$Users = new Users();
$users->getArray("IDCompanies=1,anotherField>10,...");
```
I'm really like the Processwire Selectors which works that way ans also support subfield selectors too
https://processwire.com/docs/selectors/#components

**Comment by delirius325** [comment]
Yeah I could work on implementing a logic to support both ways.
